import type { Metadata } from "next";
import { Poppins, Lora, Fira_Code } from "next/font/google";

import "./globals.css";
import { Navigation } from "@/components/navbar";

const poppins = Poppins({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // Tilføj de weights du vil bruge
});

const lora = Lora({
    variable: "--font-serif",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const firaCode = Fira_Code({
    variable: "--font-mono",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} ${lora.variable} ${firaCode.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    );
}
